version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
     - db:db
    ports:
      - "8080:80"

  omeka:
    depends_on:
      - db
    build: ./
    volumes:
      - omeka-files:/var/www/html/files
    image: omeka
    ports:
      - "80:80"
    restart: always
volumes:
  mysql-data:
    driver: local
  omeka-files:
    driver: local
