version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
     - db:db
    ports:
      - "8080:80"

  omeka:
    depends_on:
      - db
      - traefik
    build: ./
    volumes:
      - omeka-files:/var/www/html/files
    image: omeka
    ports:
      - "80:80"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omeka.rule=Host(`archivosdelsur.fiqus.coop`)"
      - "traefik.http.routers.omeka.entrypoints=websecure"
      - "traefik.http.routers.omeka.tls.certresolver=myresolver"
      - "traefik.http.middlewares.omeka.redirectscheme.scheme=https"
      - "traefik.http.middlewares.omeka.redirectscheme.permanent=true"

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=joaquinmansilla+1@fiqus.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8082:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  mysql-data:
    driver: local
  omeka-files:
    driver: local
