version: "2"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    volumes:
      - mysql-data:/var/lib/mysql

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: omeka
      PMA_PASSWORD: omeka
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"

  omeka:
    # tu Dockerfile actual
    build: ./
    image: omeka
    restart: always
    depends_on:
      - db
    # sin puertos hacia afuera: sólo expone internamente
    volumes:
      - omeka-files:/var/www/html/files

  caddy:
    image: caddy:2
    restart: always
    depends_on:
      - omeka
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
      - ./caddy-config:/config

volumes:
  mysql-data:
    driver: local
  omeka-files:
    driver: local
